import { randomUUID } from "node:crypto";
export const SCHEMA_VERSION=1;
const text=value=>String(value??"").trim();
export function createProject({title="Untitled screenshot",image=null,createdAt=new Date().toISOString()}={}){return{schemaVersion:SCHEMA_VERSION,id:randomUUID(),title:text(title)||"Untitled screenshot",createdAt,image,view:{scale:1,offsetX:0,offsetY:0},annotations:[],localText:[]};}
export function normalizeRect({x,y,width,height},imageWidth,imageHeight){const rect={x:Number(x)/imageWidth,y:Number(y)/imageHeight,width:Number(width)/imageWidth,height:Number(height)/imageHeight};for(const [name,value]of Object.entries(rect))if(!Number.isFinite(value)||value<0||value>1)throw new Error(`Region ${name} must be normalized from 0 to 1.`);if(rect.width===0||rect.height===0||rect.x+rect.width>1||rect.y+rect.height>1)throw new Error("Region must remain within the image.");return rect;}
export function scaleRect(rect,imageWidth,imageHeight){return{x:rect.x*imageWidth,y:rect.y*imageHeight,width:rect.width*imageWidth,height:rect.height*imageHeight};}
export function validateAnnotation(input){const rect=input.rect??{},label=text(input.label);if(!label)throw new Error("Annotation label is required.");for(const field of ["x","y","width","height"]){const value=Number(rect[field]);if(!Number.isFinite(value)||value<0||value>1)throw new Error("Annotation coordinates must be normalized values from 0 to 1.");}if(rect.width===0||rect.height===0||Number(rect.x)+Number(rect.width)>1||Number(rect.y)+Number(rect.height)>1)throw new Error("Annotation region is invalid.");return{id:input.id??randomUUID(),label,notes:text(input.notes)||null,rect:{x:Number(rect.x),y:Number(rect.y),width:Number(rect.width),height:Number(rect.height)},createdAt:text(input.createdAt)||new Date().toISOString()};}
export function addAnnotation(project,input){return{...project,annotations:[...project.annotations,validateAnnotation(input)]};}
export function validateProject(value){if(Number(value.schemaVersion)!==SCHEMA_VERSION)throw new Error(`Unsupported project schema; expected ${SCHEMA_VERSION}.`);const image=value.image??null;if(image!==null&&(!Number.isFinite(Number(image.width))||!Number.isFinite(Number(image.height))||Number(image.width)<=0||Number(image.height)<=0||!text(image.dataUrl)))throw new Error("Project image metadata is invalid.");const project=createProject({title:value.title,image,createdAt:value.createdAt});return{...project,id:text(value.id)||project.id,view:{scale:Number(value.view?.scale)||1,offsetX:Number(value.view?.offsetX)||0,offsetY:Number(value.view?.offsetY)||0},annotations:(value.annotations??[]).map(validateAnnotation),localText:Array.isArray(value.localText)?value.localText.map(item=>({text:text(item.text),rect:item.rect??null})):[]};}
export function serializeProject(project){return `${JSON.stringify(validateProject(project),null,2)}\n`;}
